# Generated by Django 4.2 on 2025-02-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_categorry_book_category'),
    ]

    operations = [
    ]
