# Generated by Django 4.2 on 2025-01-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='discount_dedline',
            new_name='offer_dedline',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='discount_price',
            new_name='offer_price',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(upload_to='book_media/'),
        ),
    ]
