# Generated by Django 4.2 on 2025-01-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_discount_dedline_book_offer_dedline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='categories',
            new_name='category',
        ),
    ]
