# Generated by Django 4.2 on 2025-01-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='data', editable=False, max_length=254),
            preserve_default=False,
        ),
    ]
